baselines:
    seed: 42
    rf_num_estimators: 128
    mlp_batch_size: 1024
    mlp_epochs: 50
    results_path: "/UniversalGNNs/results/"

encoders:
    encoder_class: "AutoEncoder"
    save_path: "/UniversalGNNs/checkpoints/encoders/"
    batch_size: 1024
    max_epochs: 50
    max_steps: 100_000
    latent_dim: 512
    load_checkpoint: true

graphbuilders:
    connectivity: 0.001
    distance_function: 2

regressors:
    latent_dim: 512

train_single:
    latent_dim: 512
    batch_size: 1024
    epochs: 1
    max_steps: 200_000
    drop_last: true
    n_layers: 4

train_universal:
    latent_dim: 512
    batch_size: 1024
    batches_per_epoch: 1000
    drop_last: true
    epochs: 50
    n_layers: 4
