baselines:
    results_path: "/UniversalGNNs/results/"
    seed: 42
    rf_num_estimators: 128
    mlp:
        batch_size: 1024
        epochs: 100
        batches_per_epoch: 330
        drop_last: true
        use_random_sampler: true
        dropout: 0

encoders:
    encoder_class: "VAE"
    save_path: "/UniversalGNNs/checkpoints/encoders/"
    batch_size: 1024
    max_epochs: 1
    max_steps: 200_000
    latent_dim: 512
    load_checkpoint: true
    train_self_supervised: true
    train_e2e: true

graphbuilders:
    connectivity: 0.001
    distance_function: 2

regressors:
    latent_dim: 512
    use_mlp: true

train_single:
    latent_dim: 512
    batch_size: 1024
    max_steps: 200_000
    drop_last: true
    n_layers: 4
    use_random_sampler: true
    batches_per_epoch: 330
    epochs: 100

train_universal:
    latent_dim: 512
    batch_size: 1024
    batches_per_epoch: 1000
    drop_last: true
    epochs: 100
    n_layers: 4
